POST http://localhost:5000/api/v1/quotes
Content-Type: application/json

{
    "username": "khoadeptraiforever",
    "password": "admspbtwoq016578",
    "quote": "Không bao giờ được dùng những lời đau lòng để làm tổn thương đến người mà bạn yêu thương vào những lúc bạn có tâm trang tồi tệ.",
    "author": "Khuyết danh"
}

###
GET http://localhost:5000/api/v1/quotes/search?author=tenkhongdau


###
GET http://localhost:5000/api/v1/quotes/random


###
GET http://localhost:5000/api/v1/quotes/

###
DELETE http://localhost:5000/api/v1/quotes/638192f2b34e34124cb1b4de