POST http://localhost:5000/api/v1/quotes
Content-Type: application/json

{
    "username": "khoadeptraiforever",
    "password": "admspbtwoq016578",
    "quote": "hừm đừng áp dụng phim vào đời sống và cũng đừng coi phim dỡ",
    "author": "tenkhongdau"

}

###
GET http://localhost:5000/api/v1/quotes/search?author=tenkhongdau


###
GET http://localhost:5000/api/v1/quotes/random


###
GET http://localhost:5000/api/v1/quotes/